FROM docker.io/library/node:25.9-alpine3.23

WORKDIR /var/www

COPY package*.json ./
RUN npm install -g @angular/cli && npm install

#COPY . .

EXPOSE 3000
VOLUME /var/www/node_modules

CMD npm run start