{{ with .Values.backend }}
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: backend 
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels: 
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: copy-app
          image: {{ .image | quote }}
          command: [ "sh", "-c", "cp -r /var/www/html/. /app-files/" ]
          volumeMounts:
            - name: app-files
              mountPath: /app-files
      containers: 
        - name: backend 
          image: {{ .image | quote }}
          ports:
            - containerPort: {{ .port | quote }}
          volumeMounts:
            - name: app-files
              mountPath: /var/www/html
          resources:
            requests:
              memory: {{ .resources.requests.memory | default "64Mi" | quote }}
              cpu: {{ .resources.requests.cpu | default "64m" | quote }}
            limits:
              memory: {{ .resources.limits.memory | default "256Mi" | quote }}
              cpu: {{ .resources.limits.cpu | default "256m" | quote }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: database-url
        {{ with .Values.nginx }}
        - name: nginx 
          image: {{ .image | quote }}
          ports:
            - containerPort: {{ .port | quote }}
          volumeMounts:
            - name: app-files
              mountPath: /var/www/html
            - name: backend-nginx-config
              mountPath: /etc/nginx/conf.d
          resources:
            requests:
              memory: {{ .resources.requests.memory | default "64Mi" | quote }}
              cpu: {{ .resources.requests.cpu | default "64m" | quote }}
            limits:
              memory: {{ .resources.limits.memory | default "256Mi" | quote }}
              cpu: {{ .resources.limits.cpu | default "256m" | quote }}
        {{ end }}
      volumes:
        - name: app-files
          emptyDir: {}
        - name: backend-nginx-config
          configMap:
            name: backend-nginx-config
{{ end }}