apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-nginx-config
data:
  default.conf: |
    server {
        listen {{ .Values.nginx.port }};
        root /var/www/html/public;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php$is_args$args;
        }

        location ~ \.php$ {
            fastcgi_pass localhost:{{ .Values.backend.port }};
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $document_root;
        }
    }
