{{ with .Values.database }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: {{ .image | quote }}
          ports:
            - containerPort: {{ .port | quote }}
          resources:
            requests:
              memory: {{ .resources.requests.memory | default "64Mi" | quote }}
              cpu: {{ .resources.requests.cpu | default "64m" | quote }}
            limits:
              memory: {{ .resources.limits.memory | default "256Mi" | quote }}
              cpu: {{ .resources.limits.cpu | default "256m" | quote }}
          volumeMounts:
            - name: database-pvc
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: {{ .databaseName | quote }}
  volumeClaimTemplates:
    - metadata:
        name: database-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .storage | quote }}
{{ end }}