{{ with .Values.frontend }}
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: frontend 
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels: 
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers: 
        - name: frontend 
          image: {{ .image | quote }}
          ports:
            - containerPort: {{ .port | quote }}
          resources:
            requests:
              memory: {{ .resources.requests.memory | default "64Mi" | quote }}
              cpu: {{ .resources.requests.cpu | default "64m" | quote }}
            limits:
              memory: {{ .resources.limits.memory | default "256Mi" | quote }}
              cpu: {{ .resources.limits.cpu | default "256m" | quote }}
          volumeMounts:
            - name: frontend-nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: frontend-nginx-config
          configMap:
            name: frontend-nginx-config
{{ end }}