apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
stringData:
{{ with .Values.database }}
  mysql-root-password: {{ .rootPassword | quote }}
  database-url: "mysql://root:{{ .rootPassword }}@database:{{ .port }}/{{ .databaseName }}"
{{ end }}