apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
stringData:
  mysql-root-password: {{ .Values.database.rootPassword | quote }}
  database-url: "mysql://root:{{ .Values.database.rootPassword }}@database:{{ .Values.database.port }}/{{ .Values.database.databaseName }}"
