apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: my-template
labels:
  app: symfony-angular-demo
objects:
  - apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: database
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: database
      template:
        metadata:
          labels:
            app: database
        spec:
          containers:
            - name: database
              image: docker.io/library/mysql:9.7-oraclelinux9
              ports:
                - containerPort: 3306
              volumeMounts:
                - name: database-pvc
                  mountPath: /var/lib/mysql
              env:
                - name: MYSQL_ROOT_PASSWORD
                  value: ${MYSQL_ROOT_PASSWORD}
                - name: MYSQL_DATABASE
                  value: ${MYSQL_DATABASE}
      volumeClaimTemplates:
        - metadata:
            name: database-pvc
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 1Gi

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: backend-nginx-config
    data:
      default.conf: |
        server {
            listen 80;
            root /var/www/html/public;
            index index.php;

            location / {
                try_files $uri $uri/ /index.php$is_args$args;
            }

            location ~ \.php$ {
                fastcgi_pass localhost:9000;   # localhost, not a K8s service
                fastcgi_split_path_info ^(.+\.php)(/.*)$;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param DOCUMENT_ROOT $document_root;
            }
        }

  - apiVersion: apps/v1
    kind: Deployment 
    metadata:
      name: backend 
    spec:
      replicas: 3
      selector:
        matchLabels: 
          app: backend
      template:
        metadata:
          labels:
            app: backend
        spec:
          initContainers:
            - name: copy-app
              image: docker.io/moukail/symfony-angular-demo-backend:latest
              command: [ "sh", "-c", "cp -r /var/www/html/. /app-files/" ]
              volumeMounts:
                - name: app-files
                  mountPath: /app-files
          containers: 
            - name: backend 
              image: docker.io/moukail/symfony-angular-demo-backend:latest
              ports:
                - containerPort: 9000
              volumeMounts:
                - name: app-files
                  mountPath: /var/www/html
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "128m"
                limits:
                  memory: "256Mi"
                  cpu: "256m"
              env:
                - name: DATABASE_URL
                  value: "mysql://${MYSQL_ROOT_USER}:${MYSQL_ROOT_PASSWORD}@database:3306/${MYSQL_DATABASE}"
            - name: nginx 
              image: docker.io/library/nginx:1.30-alpine3.23-slim
              ports:
                - containerPort: 80
              volumeMounts:
                - name: app-files
                  mountPath: /var/www/html
                - name: backend-nginx-config
                  mountPath: /etc/nginx/conf.d
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "64m"
                limits:
                  memory: "128Mi"
                  cpu: "128m"
          volumes:
            - name: app-files
              emptyDir: {}
            - name: backend-nginx-config
              configMap:
                name: backend-nginx-config

  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: database-migrations
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: database-migrations
              image: docker.io/moukail/symfony-angular-demo-backend:latest
              command: [ "php", "bin/console", "doctrine:migrations:migrate", "--no-interaction"]

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: frontend-nginx-config
    data:
      default.conf: |
        server {
            listen 80;
            server_name localhost;
            root /usr/share/nginx/html;
            index index.html index.htm;

            location / {
                try_files $uri $uri/ /index.html;
            }
        }

  - apiVersion: apps/v1
    kind: Deployment 
    metadata:
      name: frontend 
    spec:
      replicas: 3
      selector:
        matchLabels: 
          app: frontend
      template:
        metadata:
          labels:
            app: frontend
        spec:
          containers: 
            - name: frontend 
              image: docker.io/moukail/symfony-angular-demo-frontend:latest
              ports:
                - containerPort: 80    
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "64m"
                limits:
                  memory: "128Mi"
                  cpu: "128m"
              volumeMounts:
                - name: frontend-nginx-config
                  mountPath: /etc/nginx/conf.d
          volumes:
            - name: frontend-nginx-config
              configMap:
                name: frontend-nginx-config

  - apiVersion: v1
    kind: Service
    metadata:
      name: database
    spec:
      clusterIP: None
      selector:
        app: database
      ports:
        - protocol: TCP
          port: 3306
          targetPort: 3306

  - apiVersion: v1
    kind: Service
    metadata:
      name: backend
    spec:
      selector:
        app: backend
      ports:
        - protocol: TCP
          port: 80
          targetPort: 80

  - apiVersion: v1
    kind: Service
    metadata:
      name: frontend
    spec:
      selector:
        app: frontend
      ports:
        - protocol: TCP
          port: 80
          targetPort: 80

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: backend
    spec:
      host: demo-default.apps-crc.testing
      path: /api
      to:
        kind: Service
        name: backend

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: frontend
    spec:
      host: demo-default.apps-crc.testing
      path: /
      to:
        kind: Service
        name: frontend
    
parameters:
  - name: MYSQL_DATABASE
    required: true
  - name: MYSQL_ROOT_USER
    required: true
    value: root 
  - name: MYSQL_ROOT_PASSWORD
    required: true