nginx:
  image: docker.io/library/nginx:1.30-alpine3.23-slim
  port: 80
  resources:
    requests:
      memory: "64Mi"
      cpu: "64m"
    limits:
      memory: "128Mi"
      cpu: "128m"

backend:
  image: docker.io/moukail/symfony-angular-demo-backend:latest
  port: 9000
  replicas: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "64m"
    limits:
      memory: "256Mi"
      cpu: "256m"

frontend:
  image: docker.io/moukail/symfony-angular-demo-frontend:latest
  port: 80
  host: demo-default.apps-crc.testing
  replicas: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "64m"
    limits:
      memory: "128Mi"
      cpu: "128m"

database:
  image: docker.io/library/mysql:9.7-oraclelinux9
  port: 3306
  replicas: 1
  rootPassword: "changeme"
  databaseName: "mydemo"
  storage: 1Gi
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "512m"
