apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- db.statefulset.yaml
- backend.deployment.yaml
- frontend.deployment.yaml
- service.yaml
- route.yaml

secretGenerator:
- literals:
  - MYSQL_ROOT_PASSWORD=p@ssw0rd123
  name: db-secret
  type: Opaque

configMapGenerator:
- files:
  - backend-nginx.conf
  name: backend-nginx-config
- files:
  - frontend-nginx.conf
  name: frontend-nginx-config
