apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- db.statefulset.yaml
- backend.deployment.yaml
- frontend.deployment.yaml
- service.yaml
- route.yaml

secretGenerator:
- name: db-secret
  type: Opaque
  literals:
    - MYSQL_ROOT_PASSWORD=p@ssw0rd123

configMapGenerator:
- name: backend-nginx-config
  files:
    - backend-nginx.conf

- name: frontend-nginx-config
  files:
    - frontend-nginx.conf
